from __future__ import annotations

# Controlled taxonomy: only these strings can be auto-detected from CV text (no hallucinated skills).
# Synonyms map to canonical names in skill_normalization / cv_skill_nlp normalization step.
SKILL_KEYWORDS: frozenset[str] = frozenset(
    {
        # Languages & runtimes
        "python",
        "java",
        "javascript",
        "typescript",
        "php",
        "ruby",
        "kotlin",
        "swift",
        "rust",
        "golang",
        "c#",
        "scala",
        # Web & APIs
        "react",
        "angular",
        "vue",
        "node",
        "fastapi",
        "django",
        "flask",
        "graphql",
        "rest api",
        # Data & persistence
        "sql",
        "postgresql",
        "mysql",
        "mongodb",
        "redis",
        "elasticsearch",
        "kafka",
        "spark",
        "snowflake",
        "databricks",
        # ML / DS
        "tensorflow",
        "pytorch",
        "scikit-learn",
        "pandas",
        "numpy",
        "nlp",
        "machine learning",
        "deep learning",
        "data analysis",
        "power bi",
        "tableau",
        # Cloud & infra
        "docker",
        "kubernetes",
        "terraform",
        "ansible",
        "jenkins",
        "aws",
        "azure",
        "gcp",
        "linux",
        "git",
        "ci/cd",
        "devops",
        "helm",
        # Collaboration & PM
        "jira",
        "confluence",
        "asana",
        "scrum",
        "agile",
        "project management",
        "spring boot",
        "spring",
        "html",
        "css",
        "next.js",
        "express",
        "laravel",
        "selenium",
        "figma",
        "blockchain",
        "cybersecurity",
        "networking",
    }
)
