from __future__ import annotations

# Minimal starter taxonomy. Expand via admin UI later.
SKILL_KEYWORDS: set[str] = {
    "python",
    "java",
    "javascript",
    "typescript",
    "react",
    "node",
    "fastapi",
    "django",
    "flask",
    "sql",
    "postgresql",
    "mysql",
    "mongodb",
    "docker",
    "kubernetes",
    "aws",
    "azure",
    "gcp",
    "tensorflow",
    "pytorch",
    "scikit-learn",
    "pandas",
    "numpy",
    "nlp",
    "spark",
    "git",
    "jira",
    "asana",
    "linux",
    "ci/cd",
    "devops",
    "data analysis",
    "machine learning",
    "deep learning",
    "project management",
    "scrum",
    "agile",
}
